# Day 3 – NumPy Fundamentals

In [4]:
import numpy as np

## Creating Arrays

In [6]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [7]:
print("1D Array:", arr1)
print("2D Array:")
print(arr2)

1D Array: [10 20 30 40 50]
2D Array:
[[1 2 3]
 [4 5 6]]


# 1.1 Create arrays from lists

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array from list:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}, Dtype: {arr_1d.dtype}")


First Element: 10
Last Element: 50


# 1.2 Create 2D array (matrix)

In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array (Matrix):")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")


2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


# 1.3 Create arrays with built-in functions

In [15]:
zeros_arr = np.zeros((3, 4))  
ones_arr = np.ones((2, 3))     
range_arr = np.arange(0, 10, 2)  
linspace_arr = np.linspace(0, 10, 5)

In [16]:
print("\nZeros array (3x4):")
print(zeros_arr)


Zeros array (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
print("\nOnes array (2x3):")
print(ones_arr)


Ones array (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(f"\nRange array (0 to 10, step 2): {range_arr}")
print(f"Linspace array (0 to 10, 5 points): {linspace_arr}")


Range array (0 to 10, step 2): [0 2 4 6 8]
Linspace array (0 to 10, 5 points): [ 0.   2.5  5.   7.5 10. ]


# 1.4 Create identity and random arrays


In [19]:
identity_arr = np.eye(3)
random_arr = np.random.rand(2, 3)
random_int_arr = np.random.randint(1, 100, size=(3, 4))

In [20]:
print("\nIdentity matrix (3x3):")
print(identity_arr)


Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
print("\nRandom array (2x3):")
print(random_arr)


Random array (2x3):
[[0.9503693  0.38762156 0.02154469]
 [0.39493382 0.18449972 0.04948187]]


In [22]:
print("\nRandom integers (3x4, between 1-100):")
print(random_int_arr)


Random integers (3x4, between 1-100):
[[96 16 89 20]
 [89 84 98 77]
 [69 51 87 85]]


# 2: INDEXING AND SLICING

In [24]:
print("\n" + "=" * 70)
print("PART 2: INDEXING AND SLICING")
print("=" * 70)


PART 2: INDEXING AND SLICING


# 2.1 Basic indexing for 1D arrays

In [25]:
arr = np.array([10, 20, 30, 40, 50])
print(f"\nOriginal array: {arr}")
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Element at index 3: {arr[3]}")


Original array: [10 20 30 40 50]
First element (index 0): 10
Last element (index -1): 50
Element at index 3: 40


# 2.2 Slicing 1D arrays

In [26]:
print(f"\nSlice arr[1:4]: {arr[1:4]}")
print(f"Slice arr[::2]: {arr[::2]}")   
print(f"Slice arr[::-1]: {arr[::-1]}")


Slice arr[1:4]: [20 30 40]
Slice arr[::2]: [10 30 50]
Slice arr[::-1]: [50 40 30 20 10]


# 2.3 Indexing 2D arrays

In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:\n{matrix}")
print(f"Element at row 1, col 2: {matrix[1, 2]}")  # Value 6
print(f"First row: {matrix[0, :]}")  # or matrix[0]
print(f"Second column: {matrix[:, 1]}")


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
Second column: [2 5 8]


# 2.4 2D array slicing

In [29]:
print(f"\nFirst 2 rows, first 2 columns:\n{matrix[0:2, 0:2]}")
print(f"Last row:\n{matrix[-1, :]}")


First 2 rows, first 2 columns:
[[1 2]
 [4 5]]
Last row:
[7 8 9]


# 2.5 Boolean indexing (conditional selection)

In [30]:
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25
print(f"\nBoolean indexing - elements > 25:")
print(f"Condition: {condition}")
print(f"Filtered array: {arr[arr > 25]}")


Boolean indexing - elements > 25:
Condition: [False False  True  True  True]
Filtered array: [30 40 50]


# 2.6 Fancy indexing (using arrays of indices)

In [31]:
arr = np.array([10, 20, 30, 40, 50, 60])
indices = np.array([0, 2, 4])
print(f"\nFancy indexing with indices {indices}:")
print(f"Selected elements: {arr[indices]}")


Fancy indexing with indices [0 2 4]:
Selected elements: [10 30 50]


# 3: MATHEMATICAL OPERATIONS

In [34]:
print("\n" + "=" * 70)
print(" 3: MATHEMATICAL OPERATIONS")
print("=" * 70)


 3: MATHEMATICAL OPERATIONS


In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# 3.1 Element-wise arithmetic operations

In [54]:
print(f"\nArray a: {a}")
print(f"Array b: {b}")
print(f"a + b: {a + b}")
print(f"a - b: {a - b}")
print(f"a * b: {a * b}")
print(f"a / b: {a / b}")
print(f"a ** 2: {a ** 2}")
print(f"np.sqrt(a): {np.sqrt(a)}")


Array a: [1 2 3 4]
Array b: [5 6 7 8]
a + b: [ 6  8 10 12]
a - b: [-4 -4 -4 -4]
a * b: [ 5 12 21 32]
a / b: [0.2        0.33333333 0.42857143 0.5       ]
a ** 2: [ 1  4  9 16]
np.sqrt(a): [1.         1.41421356 1.73205081 2.        ]


# 3.2 Broadcasting (operations with scalars)

In [55]:
print(f"\nBroadcasting:")
print(f"a + 10: {a + 10}")
print(f"a * 2: {a * 2}")
print(f"a / 2: {a / 2}")


Broadcasting:
a + 10: [11 12 13 14]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]


# 3.3 2D mathematical operations

In [56]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

In [57]:
print(f"\nMatrix a:\n{matrix_a}")
print(f"Matrix b:\n{matrix_b}")
print(f"\nElement-wise multiplication:\n{matrix_a * matrix_b}")
print(f"\nMatrix multiplication (dot product):\n{np.dot(matrix_a, matrix_b)}")


Matrix a:
[[1 2]
 [3 4]]
Matrix b:
[[5 6]
 [7 8]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication (dot product):
[[19 22]
 [43 50]]


# 3.4 Aggregate functions

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"\nArray: {arr}")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Std Dev: {np.std(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
Mean: 5.5
Median: 5.5
Std Dev: 2.8722813232690143
Min: 1
Max: 10


# 3.5 Operations along axes (for 2D arrays)

In [46]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nMatrix:\n{matrix}")
print(f"Sum along rows (axis=1): {np.sum(matrix, axis=1)}")
print(f"Sum along columns (axis=0): {np.sum(matrix, axis=0)}")
print(f"Mean along axis=0: {np.mean(matrix, axis=0)}")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum along rows (axis=1): [ 6 15 24]
Sum along columns (axis=0): [12 15 18]
Mean along axis=0: [4. 5. 6.]


# PART 4: PRACTICE EXERCISES WITH SOLUTIONS

In [47]:
print("\n" + "=" * 70)
print("PART 4: PRACTICE EXERCISES")
print("=" * 70)


PART 4: PRACTICE EXERCISES


Exercise 1: Create and manipulate an array

In [49]:
print("\n--- Exercise 1: Create and manipulate array ---")
arr = np.arange(1, 11)
print(f"Array (1-10): {arr}")
print(f"Square each element: {arr ** 2}")
print(f"Elements greater than 5: {arr[arr > 5]}")


--- Exercise 1: Create and manipulate array ---
Array (1-10): [ 1  2  3  4  5  6  7  8  9 10]
Square each element: [  1   4   9  16  25  36  49  64  81 100]
Elements greater than 5: [ 6  7  8  9 10]


Exercise 2: 2D array operations

In [50]:
print("\n--- Exercise 2: 2D array operations ---")
matrix = np.random.randint(1, 100, size=(4, 3))
print(f"Random matrix (4x3):\n{matrix}")
print(f"Column means: {np.mean(matrix, axis=0)}")
print(f"Row sums: {np.sum(matrix, axis=1)}")


--- Exercise 2: 2D array operations ---
Random matrix (4x3):
[[87 78 68]
 [ 3 66 38]
 [59 59 50]
 [86 87 64]]
Column means: [58.75 72.5  55.  ]
Row sums: [233 107 168 237]


Exercise 3: Array reshaping

In [51]:
print("\n--- Exercise 3: Array reshaping ---")
arr = np.arange(1, 13)
print(f"Original array: {arr}")
reshaped = arr.reshape(3, 4)
print(f"Reshaped to (3, 4):\n{reshaped}")


--- Exercise 3: Array reshaping ---
Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Exercise 4: Concatenation and stacking

In [52]:
print("\n--- Exercise 4: Concatenation ---")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat = np.concatenate([arr1, arr2])
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Concatenated: {concat}")


--- Exercise 4: Concatenation ---
arr1: [1 2 3]
arr2: [4 5 6]
Concatenated: [1 2 3 4 5 6]


Exercise 5: Statistical analysis

In [53]:
print("\n--- Exercise 5: Statistical analysis ---")
data = np.array([23, 45, 56, 78, 23, 45, 67, 89, 12, 34])
print(f"Data: {data}")
print(f"Mean: {np.mean(data):.2f}")
print(f"Std Dev: {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")
print(f"Q1 (25%): {np.percentile(data, 25)}")
print(f"Q3 (75%): {np.percentile(data, 75)}")


--- Exercise 5: Statistical analysis ---
Data: [23 45 56 78 23 45 67 89 12 34]
Mean: 47.20
Std Dev: 24.00
Variance: 575.96
Q1 (25%): 25.75
Q3 (75%): 64.25
